[package]
name = "ezytutors"
version = "0.1.0"
edition = "2021"

[dependencies]


[workspace]
members = ["tutor-nodb", "tutor-db"]
#to set the tutor-db as the project root
#you have to type export PROJECT_ROOT=. in the terminal in tutor-db folder